import React, { useState } from 'react';

// Define a type for the FAQ item
type FAQItem = {
    question: string;
    answer: string;
    isOpen: boolean;
};

function FAQ() {
    const [faqItems, setFaqItems] = useState<FAQItem[]>([
        {
            question: 'What is PlasmaWorld?',
            answer: 'PlasmaWorld is a revolutionary NFT project that aims to create a comprehensive ecosystem for NFT holders. By utilizing funds generated from NFT sales, we plan to establish a diverse range of businesses, including web3-based affiliate marketing, real estate investments, sustainable farming initiatives, production companies, and open-source development for our NFT community. Our goal is to empower our NFT holders with a range of sustainable technology solutions and opportunities for growth.',
            isOpen: false,
        },
        {
            question: 'What are the Benefits from Holding the PlasmaWorld?',
            answer: 'The 19,800 Plasma World Foundations NFTs in circulation embody a 20% ownership slice of the expansive ecosystem. Holders of these NFTs not only receive a proportional share of the quarterly cash flow but also unlock the prospect of becoming active business owners. These NFTs open the door for individuals to engage in a community-driven ecosystem, fostering the exchange of ideas and collaborative development, ultimately empowering them to shape and thrive within innovative ventures.',
            isOpen: false,
        },
        {
            question: 'How does PlasmaW3bWorld use the funds we Generate from the Ecosystem?',
            answer: "We're dedicated to building one of the largest NFT ecosystems worldwide. To achieve this goal, we've implemented a streamlined system with seven designated wallets, each allocated a specific portion. This transparent approach ensures that our community remains at the forefront, driving the ecosystem's direction to meet everyone's needs.",
            isOpen: false,
        },
        {
            question: 'How does PlasmaWorldFoundation Pay the Nft Holders?',
            answer: 'PlasmaWorld pays its NFT holders on a quarterly basis by distributing a proportionate share of the revenue generated by the ecosystem. The distribution is based on the percentage of NFTs held by each individual. This distribution system allows for a fair and transparent distribution of funds, and ensures that all NFT holders have the opportunity to benefit from the success of the ecosystem.',
            isOpen: false,
        },
    ]);

    const toggleFAQ = (index: number) => {
        setFaqItems((prevItems) =>
            prevItems.map((item, i) =>
                i === index ? { ...item, isOpen: !item.isOpen } : item
            )
        );
    };

    return (
        <div className='bg-[#000509] py-24 lg:py-32 text-white'>
            <div className='max-w-7xl mx-auto px-7 2xl:px-0'>
                <h2 className='text-3xl text-sky-500 text-center font-bold'>
                    FAQ
                </h2>

                <div className='my-10'>
                    {faqItems.map((item, index) => (
                        <div key={index} className="collapse collapse-arrow bg-sky-500 mb-2">
                            <input type="checkbox" id={`faq-${index}`} checked={item.isOpen} onChange={() => toggleFAQ(index)} />
                            <label htmlFor={`faq-${index}`} className="collapse-title text-lg font-medium">
                                {item.question}
                            </label>
                            <div className="collapse-content">
                                <p className='text-white-500'>{item.answer}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}

export default FAQ;
